language: java

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.jabba/jdk'

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cmake3
            - g++
    - os: osx
      addons:
        homebrew:
          packages:
            - cmake

script: mvn --batch-mode

after_success:
  - bash <(curl -s https://codecov.io/bash)


