language: java

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.jabba/jdk'

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - cmake3
            - g++
    - os: linux
      env: MVN_PROFILE='mingw32'
      addons:
        apt:
          packages:
            - cmake3
            - g++-mingw-w64-i686
    - os: linux
      env: MVN_PROFILE='mingw64'
      addons:
        apt:
          packages:
            - cmake3
            - g++-mingw-w64-x86-64
    - os: linux
      env: MVN_PROFILE='armsf,armtrusty'
      addons:
        apt:
          packages:
            - cmake3
            - g++-arm-linux-gnueabi
    - os: linux
      env: MVN_PROFILE='armhf,armtrusty'
      addons:
        apt:
          packages:
            - cmake3
            - g++-arm-linux-gnueabihf
    - os: osx
      addons:
        homebrew:
          packages:
            - cmake

script: if [ -z "$MVN_PROFILE" ]; then mvn --batch-mode; else mvn -P "$MVN_PROFILE"; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)


