language: java

cache:
  directories:
    - '$HOME/.m2'
    - '$HOME/.jabba/jdk'


addons:
  apt:
    packages:
    - cmake

script: mvn --fail-never --batch-mode test

after_success:
  - bash <(curl -s https://codecov.io/bash)


